# Site settings
title: Open Business Intelligence
email: openbusinessintelligence@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Open Business Intelligence is a collection of tools and facilities that help you make the most out of your business intelligence and data warehouse infrastructure.
baseurl: ""
url: "http://openbusinessintelligence.github.io/"
twitter_username: openbis
github_username:  openbusinessintelligence

# Build settings
markdown: kramdown
